#!/bin/sh
### BEGIN INIT INFO
# Provides:          x_img_mon
# Required-Start:    $local_fs $network $remote_fs
# Required-Stop:     $local_fs $network $remote_fs
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Description:       This is start the image monitor service
### END INIT INFO

PIDFILE=/var/run/x_img_mon.pid
LOGFILE=/var/log/x_img_mon.log

start() {
  if [ -f "$PIDFILE" ]; then
    echo 'Service already running'
  else
    echo 'Starting service…'
    python3 /home/rahuja/Exclusive/NYU/isp/Image_Monitor/run_img_monitor.py &
    touch $PIDFILE
    echo 'Service started'
  fi
}

stop() {
  if [ ! -f "$PIDFILE" ]; then
    echo 'Service not running'
  else
    echo 'Stopping service…'
    PID= pidof /home/rahuja/Exclusive/NYU/isp/Image_Monitor/run_img_monitor.py
    kill -9 $PID && rm -f "$PIDFILE"
    echo 'Service stopped'
  fi
}

status() {
  if [ -f "$PIDFILE" ]; then
    echo 'Service already running'
  else
    echo 'Service was not started yet'
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
esac

# Author: Sai Rajeev
